language: go
go:
  - 1.13.3
dist: bionic
sudo: required

before_install:
  - sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu/ xenial main restricted universe" >> /etc/apt/sources.list'
  - sudo apt-get update
  - sudo apt-get install -y pkg-config libgit2-dev
  - sudo apt-get clean

install:
  - go get github.com/apuigsech/seekret/cmd/seekret
